// resources/js/vue/layouts/AuthCardLayout.vue
<script setup lang="ts">
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card';

import AlertMessage from '@/components/AlertMessage.vue';
import AppLogo from '@/components/AppLogo.vue';
import Footer from '@/components/Footer.vue';
import PageTransition from '@/components/PageTransition.vue';
import { Head, Link } from '@inertiajs/vue3';

defineProps<{
    title?: string;
    description?: string;
    cardClass?: string | object;
}>();
</script>

<template>
    <div class="flex min-h-screen flex-col items-center gap-6">
        <div class="mt-6">
            <Head :title="title" />
            <Link :href="route('index')" class="mt-6 font-medium">
                <AppLogo size="md" :showText="true" />
            </Link>
        </div>

        <div class="flex w-full grow flex-col items-center">
            <div
                class="w-full px-4 min-[450px]:w-auto min-[450px]:min-w-md min-[450px]:px-0"
            >
                <Card :class="cardClass">
                    <CardHeader class="px-8 text-center">
                        <CardTitle class="text-2xl">
                            {{ title }}
                        </CardTitle>
                        <CardDescription>
                            {{ description }}
                        </CardDescription>
                    </CardHeader>
                    <CardContent class="px-8">
                        <PageTransition>
                            <AlertMessage
                                :message="
                                    $page.props.status || $page.props.error
                                "
                                :variant="
                                    $page.props.status ? 'success' : 'error'
                                "
                                class="mt-4"
                                data-testid="alert"
                            />
                            <slot />
                        </PageTransition>
                    </CardContent>
                </Card>
            </div>
            <slot name="outside" />
        </div>
        <Footer class="mt-16 w-full pt-8" />
    </div>
</template>

// resources/js/react/layouts/AuthCardLayout.tsx
import AlertMessage from '@/components/AlertMessage';
import AppLogo from '@/components/AppLogo';
import Footer from '@/components/Footer';
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card';
import { Head, Link, usePage } from '@inertiajs/react';
import type { ReactNode } from 'react';

interface AuthCardLayoutProps {
    title?: string;
    description?: string;
    cardClass?: string;
    children: ReactNode;
    outside?: ReactNode;
}

export default function AuthCardLayout({
    title,
    description,
    cardClass,
    children,
    outside,
}: AuthCardLayoutProps) {
    const page = usePage();
    const status = page.props.status as string | undefined;
    const error = page.props.error as string | undefined;

    return (
        <div className="flex h-screen flex-col items-center gap-6">
            <div className="mt-6">
                <Head title={title} />
                <Link href={route('index')} className="mt-6 font-medium">
                    <AppLogo size="md" showText={true} />
                </Link>
            </div>

            <div className="flex w-full grow flex-col items-center">
                <div className="w-full px-4 min-[450px]:w-auto min-[450px]:min-w-md min-[450px]:px-0">
                    <Card className={cardClass}>
                        <CardHeader className="px-8 text-center">
                            <CardTitle className="text-2xl">{title}</CardTitle>
                            <CardDescription>{description}</CardDescription>
                        </CardHeader>
                        <CardContent className="px-8">
                            {status || error ? (
                                <div data-testid="alert">
                                    <AlertMessage
                                        message={status || error}
                                        variant={status ? 'success' : 'error'}
                                    />
                                </div>
                            ) : null}
                            {children}
                        </CardContent>
                    </Card>
                </div>
                {outside}
            </div>
            <Footer />
        </div>
    );
}
